check50:
  files: &check50_files
    - !exclude "*"
    - !include "*.c"
    - !include "*.h"
    - !exclude "speller.c"
    - !require dictionary.c

submit50:
  files: *check50_files
  remote:
    message: "Go to https://speller.cs50.net/challenge/{commit_hash} to see your results!"
    callback: "https://speller.cs50.net/challenge"
