COURSES = ["cs50x", "python", "ai", "web"]
CONTENT_TYPES = ["labs_checks", "labs_code", "labs_scripts", "labs_specifications", "lectures_code", "lectures_scripts", "lectures_slides", "notes", "psets", "psets_checks", "psets_code", "psets_specifications", "shorts_scripts", "shorts_slides", "specifications", "walkthroughs_scripts", "walkthroughs_slides", "pages"]
LANGUAGES = ["portuguese", "french", "spanish"]
NOTES = "notes"
SPECIFICATIONS = "specifications"
MANUAL = "manual"
PSETS = "psets"
PSETS_CODE= "psets_code"
LABS_CODE = "labs_code"
PSETS_CHECKS = "psets_checks"
LABS_CHECKS = "labs_checks"
